export const SYNC = {
  MAX_RETRIES: 5,
  BATCH_SIZE: 20,
  INITIAL_BACKOFF_MS: 1000,
  MAX_BACKOFF_MS: 30000,
  PERIODIC_CHECK_MS: 30000,
} as const

export const SECURITY = {
  MIN_PASSWORD_LENGTH: 12,
  SALT_BYTES: 16,
  PIN_MAX_ATTEMPTS: 3,
  LOCKOUT_BASE_SECONDS: 30,
  LOCKOUT_MAX_SECONDS: 300,
} as const

export const STORAGE = {
  DB_VERSION: 3,
  SYNC_CLEANUP_DAYS: 7,
} as const
