/**
 * Store Manifest — Every Zustand store, its shape, and its wiring.
 *
 * Fields: state field names with types.
 * Actions: method names with brief descriptions.
 * Middleware: persist, devtools, custom.
 * Cross-store refs: which other stores this one reads/writes.
 * Services: lib/ modules called by store actions.
 */

export const stores = {
  useAuthStore: {
    path: 'stores/useAuthStore.ts',
    purpose: 'User identity, auth state, profile, roles, device role, session, Signal readiness',
    fields: {
      user: 'User | null',
      loading: 'boolean',
      isGuest: 'boolean',
      profile: 'UserTypes',
      roles: 'string[]',
      clinicId: 'string | null',
      isDevRole: 'boolean',
      isSupervisorRole: 'boolean',
      isProviderRole: 'boolean',
      isPasswordRecovery: 'boolean',
      needsPasswordSetup: 'boolean',
      deviceRole: 'DeviceRole | null',
      localSession: 'LocalSession | null',
      sessionReady: 'boolean',
      signalReady: 'boolean',
    },
    actions: [
      'init', 'continueAsGuest', 'signOut', 'patchProfile',
      'refreshProfile', 'setPasswordRecovery', 'setNeedsPasswordSetup',
    ],
    middleware: [],
    crossStoreRefs: {
      reads: [],
      writes: ['useCallStore', 'useCalendarStore', 'useMessagingStore'],
    },
    services: [
      'supabase', 'pinService', 'biometricService', 'cacheService',
      'authService', 'cryptoService', 'activityHeartbeat', 'secureStorage',
      'sessionCleanup', 'pushNotificationService', 'calendarEventStore',
      'clinicUsersCache', 'lora/loraDb',
      'signal/signalInit', 'signal/keyManager', 'signal/session',
      'signal/messageStore', 'signal/outboundQueue', 'signal/backupService',
      'signal/vaultDevice', 'signal/clinicVaultDevice', 'signal/signalService',
    ],
  },

  useNavigationStore: {
    path: 'stores/useNavigationStore.ts',
    purpose: 'UI state: drawers, menus, search, columns, mobile breakpoint, view routing',
    fields: {
      viewState: "'main' | 'subcategory' | 'questions'",
      selectedCategory: 'catDataTypes | null',
      selectedSymptom: 'subCatDataTypes | null',
      selectedGuideline: '{ type, id, symptomId } | null',
      columnAPanel: 'number',
      isMenuOpen: 'boolean',
      showSettings: 'boolean',
      isSearchExpanded: 'boolean',
      isImportExpanded: 'boolean',
      showSymptomInfo: 'boolean',
      showKnowledgeBase: 'boolean',
      kbInitialView: 'string | null',
      kbInitialMedication: 'medListTypes | null',
      kbInitialScreenerId: 'string | null',
      isWriteNoteVisible: 'boolean',
      writeNoteData: 'WriteNoteData | null',
      showTrainingDrawer: 'boolean',
      trainingDrawerTaskId: 'string | null',
      showMessagesDrawer: 'boolean',
      showPropertyDrawer: 'boolean',
      showLoRaDrawer: 'boolean',
      showMapOverlayDrawer: 'boolean',
      showCalendarDrawer: 'boolean',
      calendarDrawerEventId: 'string | null',
      showAdminDrawer: 'boolean',
      showSupervisorDrawer: 'boolean',
      showProviderDrawer: 'boolean',
      isMobile: 'boolean',
    },
    actions: [
      'init', 'handleNavigation', 'handleBackClick', 'toggleMenu', 'closeMenu',
      'setShowSettings', 'toggleSearchExpanded',
      'setSearchExpanded', 'toggleImportExpanded', 'setImportExpanded',
      'expandSearchOnMobile', 'toggleSymptomInfo', 'setShowSymptomInfo',
      'setShowKnowledgeBase', 'setShowTrainingDrawer', 'setShowMessagesDrawer',
      'setShowPropertyDrawer', 'setShowLoRaDrawer', 'setShowMapOverlayDrawer',
      'setShowCalendarDrawer', 'openCalendarEvent', 'clearCalendarDrawerEventId',
      'setShowAdminDrawer', 'setShowSupervisorDrawer',
      'setShowProviderDrawer', 'openWriteNote', 'closeWriteNote', 'resetToMain',
    ],
    middleware: [],
    crossStoreRefs: { reads: [], writes: [] },
    services: [],
  },

  useMessagingStore: {
    path: 'stores/useMessagingStore.ts',
    purpose: 'Conversations, unread counts, groups, tombstones, device IDs',
    fields: {
      conversations: 'Record<string, DecryptedSignalMessage[]>',
      unreadCounts: 'Record<string, number>',
      groups: 'Record<string, GroupInfo>',
      sendingMap: 'Record<string, boolean>',
      deletedConversations: 'Record<string, string>',
      localDeviceId: 'string | null',
      clinicDeviceId: 'string | null',
      localUserId: 'string | null',
      systemGroupIds: 'Set<string>',
      hydrated: 'boolean',
    },
    actions: [
      'addMessage', 'updateMessageStatus', 'updateMessageContent',
      'removeOptimisticMessage', 'markAsRead', 'applyReadSync',
      'applyDeliveryReceipt', 'deleteMessages', 'removeMessagesByOriginIds',
      'deleteConversation', 'setConversations', 'setSending', 'setGroups',
      'addGroup', 'removeGroup', 'setUnreadCount', 'setLocalDeviceId',
      'setClinicDeviceId', 'setSystemGroupIds', 'hydrateFromIdb', 'clearAll',
    ],
    selectors: [
      'useConversation(key)', 'useUnreadCount(key)',
      'useTotalUnread()', 'useIsSending(key)', 'useGroups()',
    ],
    middleware: [],
    crossStoreRefs: { reads: [], writes: [] },
    services: ['signal/messageStore', 'signal/keyManager'],
  },

  useCalendarStore: {
    path: 'stores/useCalendarStore.ts',
    purpose: 'Calendar events, views, personnel, IDB persistence middleware',
    fields: {
      currentView: "'month' | 'day' | 'troops'",
      selectedDate: 'string',
      selectedEventId: 'string | null',
      editingEventId: 'string | null',
      showEventForm: 'boolean',
      categoryFilter: 'EventCategory[] | null',
      events: 'CalendarEvent[]',
      rosterSearchQuery: 'string',
      showRosterMobile: 'boolean',
      personnelFilter: 'string[]',
      monthLabel: 'string',
      hydrated: 'boolean',
    },
    actions: [
      'setView', 'setSelectedDate', 'selectEvent', 'setEditingEvent',
      'setShowEventForm', 'setCategoryFilter', 'addEvent', 'updateEvent',
      'removeEvent', 'moveEvent', 'setEvents', 'assignPersonnel',
      'unassignPersonnel', 'setRosterSearchQuery', 'setShowRosterMobile',
      'togglePersonnelFilter', 'clearPersonnelFilter', 'setMonthLabel',
      'setHydrated',
    ],
    middleware: ['calendarPersist (custom IDB write middleware)'],
    crossStoreRefs: { reads: [], writes: [] },
    services: ['calendarEventStore'],
    note: 'Persisted actions: addEvent, updateEvent, removeEvent, moveEvent, assignPersonnel, unassignPersonnel',
  },

  useTC3Store: {
    path: 'stores/useTC3Store.ts',
    purpose: 'Trauma casualty card (DD1380) form state — injuries, treatments, vitals, evacuation',
    fields: {
      card: 'TC3Card',
      selectedSection: 'TC3Section',
      wizardStep: 'number',
    },
    actions: [
      'setSelectedSection', 'nextWizardStep', 'prevWizardStep', 'setWizardStep',
      'resetCard', 'updateCasualty', 'toggleMechanism', 'setMechanismOther',
      'addInjury', 'updateInjury', 'removeInjury',
      'linkTreatmentToInjury', 'unlinkTreatmentFromInjury',
      'addTourniquet', 'updateTourniquet', 'removeTourniquet',
      'addHemostatic', 'updateHemostatic', 'removeHemostatic',
      'updateAirway', 'updateNeedleDecomp', 'updateChestSeal',
      'updateChestTube', 'updateRespirationO2',
      'addIVAccess', 'removeIVAccess', 'addFluid', 'removeFluid',
      'addBloodProduct', 'removeBloodProduct',
      'addMedication', 'updateMedication', 'removeMedication',
      'addVitalSet', 'updateVitalSet', 'removeVitalSet',
      'setAVPU', 'setGCS', 'updateEvacuation', 'updateOther',
      'updateFirstResponder', 'setNotes',
    ],
    middleware: [],
    crossStoreRefs: { reads: [], writes: [] },
    services: ['Utilities/bodyRegionMap'],
  },

  usePropertyStore: {
    path: 'stores/usePropertyStore.ts',
    purpose: 'Equipment items, locations, holders, canvas navigation, zone selection',
    fields: {
      items: 'LocalPropertyItem[]',
      locations: 'LocalPropertyLocation[]',
      holders: 'Map<string, HolderInfo>',
      clinicMembers: 'HolderInfo[]',
      isLoading: 'boolean',
      isSyncing: 'boolean',
      clinicId: 'string | null',
      selectedItem: 'LocalPropertyItem | null',
      editingItem: 'LocalPropertyItem | null',
      selectedZoneId: 'string | null',
      canvasStack: 'string[]',
      rootLocationId: 'string | null',
      defaultLocationId: 'string | null',
      tagVersion: 'number',
      transitionState: "'idle' | 'zooming-in' | 'zooming-out'",
      holderFilter: 'string | null',
    },
    actions: [
      'selectItem', 'setEditingItem', 'selectZone', 'navigateInto',
      'navigateBack', 'navigateToPath', 'setRootLocationId',
      'setDefaultLocationId', 'bumpTagVersion', 'setTransitionState',
      'setHolderFilter', 'init', 'addItem', 'editItem', 'removeItem',
      'addLocation', 'editLocation', 'removeLocation',
      'refreshItems', 'refreshLocations',
    ],
    middleware: [],
    crossStoreRefs: { reads: ['useAuthStore'], writes: [] },
    services: ['supabase', 'propertyService', 'syncService'],
  },

  useCallStore: {
    path: 'stores/useCallStore.ts',
    purpose: 'Voice/video call status, peer info, mute/video state',
    fields: {
      status: 'CallStatus',
      direction: 'CallDirection | null',
      peer: 'CallPeer | null',
      connectedAt: 'number | null',
      endReason: 'string | null',
      isMuted: 'boolean',
      callMode: 'CallMode',
      isVideoOff: 'boolean',
    },
    actions: [
      'startRinging', 'setConnecting', 'setConnected',
      'endCall', 'toggleMute', 'toggleVideo', 'reset',
    ],
    selectors: ['selectIsInCall', 'selectShowCallUI'],
    middleware: [],
    crossStoreRefs: { reads: [], writes: [] },
    services: [],
  },

  useInvalidationStore: {
    path: 'stores/useInvalidationStore.ts',
    purpose: 'Domain generation counters for cache invalidation / refetch triggers',
    fields: {
      generations: 'Record<Domain, number>',
    },
    actions: ['invalidate'],
    domains: ['users', 'clinics', 'requests', 'properties', 'calendar', 'training', 'messaging'],
    middleware: [],
    crossStoreRefs: { reads: [], writes: [] },
    services: [],
    note: 'Exports standalone invalidate() and useInvalidation() hook',
  },

  useNavPreferencesStore: {
    path: 'stores/useNavPreferencesStore.ts',
    purpose: 'Custom nav order, starred/hidden actions, pinned KB items (persisted)',
    fields: {
      customOrder: 'string[] | null',
      starred: 'string[]',
      hidden: 'string[]',
      pinnedKB: 'string[]',
    },
    actions: ['toggleStar', 'toggleHide', 'moveItem', 'togglePinKB', 'resetToDefault'],
    middleware: ['persist (localStorage: nav-preferences)'],
    crossStoreRefs: { reads: [], writes: [] },
    services: [],
  },
} as const;

export type StoreId = keyof typeof stores;
